[toolchain]
# Changing channel requires changes to
# 1st https://github.com/luigi311/tanoshi-builder
# 2nd Here and then create a release
# 3rd https://github.com/luigi311/tanoshi-extensions
channel = "1.79.0"
targets = [ "wasm32-unknown-unknown" ]
