[[proxy]]
backend = "http://localhost:3030/graphql"

[[proxy]]
backend = "ws://localhost:3030/ws"
ws = true

[[proxy]]
backend = "http://localhost:3030/image"

[tools]
sass = "1.93.2"
wasm_bindgen = "0.2.108"
wasm_opt = "version_125"

[serve]
addresses = ["0.0.0.0"]
