[package]
name = "tanoshi-lib"
version = "0.25.1"
authors = ["Muhammad Fadhlika <fadhlika@gmail.com>"]
edition = "2018"
description = "Tanoshi library"
repository = "https://github.com/faldez/tanoshi"
license = "MIT"
readme = "README.md"
exclude = [".github/*"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
tanoshi-util = { path = "../tanoshi-util", version = "0.3.0" }
thiserror = "1"

[dev-dependencies]
ron = "0.6.4"
